### ISSUE TITLE
Fix incompatible python lib

### ISSUE THREAD

**Issue by alock** [owenwater/alfred-cal#14]
Do you have a simple fix to allow me to enable this workflow again?

<img width="365" alt="python-lib" src="https://user-images.githubusercontent.com/6048048/30144441-16937ec0-9340-11e7-80d6-181d799d0b3b.png">

https://www.alfredapp.com/help/troubleshooting/incompatible-python-workflow-library/

**Comment by oorahduc** [comment]
@alock - go here: https://github.com/deanishe/alfred-fixum

Download the fixum workflow, enable debugging on it, and run the Dry Run fixum workflow in alfred. In the debug console it will tell you what workflows currently use an outdated version of the python workflow lib. Once you're satisfied that the workflows are safe to update, run the "Fix Workflows" workflow in fixum. This will update all workflows you have with the new version of the python lib.
  
PR submitted to make this unnecessary.

**Comment by alock** [comment]
I forgot about this issue, thanks for the workaround.  However it was already working without those steps I will close.
