### ISSUE TITLE
Mac Big Sur

### ISSUE THREAD

**Issue by thejackbeck** [owenwater/alfred-cal#20]
This is my favorite Alfred workflow!!!  Unfortunately, it stopped working when I installed OSX 11.  I know that you aren't maintaining it anymore but I'm wondering if you have any advice on how to make it work on Big Sur.

**Comment by cleobis** [comment]
Does this work for you? https://github.com/cleobis/alfred-cal/releases/latest

**Comment by thejackbeck** [comment]
Yes it did indeed work.
