### ISSUE TITLE
Give config option to start weeks on mondays

### ISSUE THREAD

**Issue by LeEnno** [owenwater/alfred-cal#4]
Would it be hard to implement an option where the user can make the week start on mondays?

BTW: great workflow, like it a lot.

**Comment by owenwater** [comment]
Hi @LeEnno 

It shouldn't be difficult. I'll add this feature soon.

**Comment by owenwater** [comment]
Hi @LeEnno 

Here is the latest [workflow](https://github.com/owenwater/alfred-cal/blob/dev/Calendar.alfredworkflow?raw=true) which supports the feature you want. Using `calconfig` for the configuration.

Owen

**Comment by LeEnno** [comment]
You rock, thx!
