### ISSUE TITLE
Showing the wrong month

### ISSUE THREAD

**Issue by KevinBatdorf** [owenwater/alfred-cal#5]
![screen shot 2015-02-05 at 12 54 21 am](https://cloud.githubusercontent.com/assets/1478421/6044950/a02e8e34-acd1-11e4-9af5-f86aaad3e78b.png)

**Comment by owenwater** [comment]
Hi @KevinBatdorf ,

The workflow doesn't support search month by name now. So it uses current month as default which is February now. I can add this feature soon. Currently, you can show April by `cal 4 1982`

**Comment by KevinBatdorf** [comment]
Ahh ok I see how it works now. Thanks for the workflow. Works how I want it to now.

**Comment by owenwater** [comment]
Hi @KevinBatdorf 

Here is the latest [workflow](https://github.com/owenwater/alfred-cal/blob/dev/Calendar.alfredworkflow?raw=true) which supports searching month by name. You can use command `cal april 1982` now.

Owen

**Comment by KevinBatdorf** [comment]
Awesome! Works like a charm. Also, I love how I can even type `cal au 2020` to see August 2020. Great job
